@startuml ライブラリ構成

actor "Your App" as apps

node "Atoms(Lv1)" as lv1
note bottom of lv1
    * IntentBuilder
    * WebViewBuilder
end note

node "Molecules(Lv2)" as lv2
note bottom of lv2
    (Now thinking)
end note

node "Organisms(Lv3)" as lv3
note bottom of lv3
    * Debugger
    * Views
end note

node "Templates(Lv4)" as lv4
note bottom of lv4
    * Baser
end note



lv3 <- lv4
lv2 <- lv3
lv1 <- lv2

apps --> lv4
apps --> lv3
apps --> lv2
apps --> lv1

@enduml
