@startuml ライブラリ構成

frame アプリ {
    [app1]
    [app2]
    [app3]
}
note right of アプリ
    各アプリ固有ロジック
end note

frame テンプレート {
    [baser]
}
note right of テンプレート
    各アプリ共通で使える骨組み
end note

frame ライブラリ {
    [debugger]
    note bottom of [debugger]
        デバッグ支援機能
    end note

    [views]
    note bottom of [views]
        UI 関連機能
    end note
}


[app1] <-- [baser]
[app2] <-- [baser]
[app3] <-- [debugger]
[app3] <-- [views]

[baser] <-- [debugger]
[baser] <-- [views]

@enduml
